### ISSUE TITLE
UnboundLocalError: local variable 'links' referenced before assignment

### ISSUE THREAD

**Issue by Darkcast** [americo/sqlifinder#6]
running on Linux kali 5.16.0-kali5-amd64 #1 SMP PREEMPT Debian 5.16.14-1kali1 (2022-03-15) x86_64 GNU/Linux

ran it against a local vuln app and i got this error 

            ___ ____         __       
  ___ ___ _/ (_) _(_)__  ___/ /__ ____
 (_-</ _ `/ / / _/ / _ \/ _  / -_) __/
/___/\_, /_/_/_//_/_//_/\_,_/\__/_/   
      /_/        ~ by @americo        v1.0 

Traceback (most recent call last):
  File "/home/kali/Downloads/sqlifinder/sqlifinder.py", line 93, in <module>
    main()
  File "/home/kali/Downloads/sqlifinder/sqlifinder.py", line 61, in main
    crawled_urls = crawler.spider(f"http://{args.domain}", 10)
  File "/home/kali/Downloads/sqlifinder/core/crawler.py", line 39, in spider
    return links
UnboundLocalError: local variable 'links' referenced before assignment

**Comment by rafay-ah** [comment]
Hi, Darkcast, 
The error is encountered when you enter complete URL. For example: https://github.com/rafay_ah
Whereas the code is written to work with domain names. So correct input for --domain argument will be  'github.com/rafay_ah ' instead of https://github.com/rafay_ah.
